// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOyOpd-c4H1pUwWFFuVd4MT3GMfEhbYW8',
    appId: '1:820371603552:web:aaa0d4af83ef913a7fc305',
    messagingSenderId: '820371603552',
    projectId: 'firenote-d72c5',
    authDomain: 'firenote-d72c5.firebaseapp.com',
    storageBucket: 'firenote-d72c5.firebasestorage.app',
    measurementId: 'G-JZZKWVCN44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_rAFfKTDcgBHOF-SqHnqm-hCjZRdek4',
    appId: '1:820371603552:android:088cac274ca1150c7fc305',
    messagingSenderId: '820371603552',
    projectId: 'firenote-d72c5',
    storageBucket: 'firenote-d72c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABHDo8d5snkWuE5Aels4JL06eKvkzdMcg',
    appId: '1:820371603552:ios:32066e0c513217dc7fc305',
    messagingSenderId: '820371603552',
    projectId: 'firenote-d72c5',
    storageBucket: 'firenote-d72c5.firebasestorage.app',
    iosBundleId: 'com.example.untitledproject',
  );
}
